### ISSUE TITLE
Crash on swipe to dismiss sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jaychang0917/SimpleRecyclerView#1]
Quite hard to reproduce, but I played with it a little, and it crashed. Here's the log:

02-05 22:28:13.343 19941-19941/com.jaychang.demo.srv E/InputEventReceiver: Exception dispatching input event.
02-05 22:28:13.372 19941-19941/com.jaychang.demo.srv E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.jaychang.demo.srv, PID: 19941
                                                                       java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                           at java.util.ArrayList.get(ArrayList.java:413)
                                                                           at com.jaychang.srv.SimpleAdapter.getCell(SimpleAdapter.java:262)
                                                                           at com.jaychang.srv.SimpleRecyclerView.getCell(SimpleRecyclerView.java:724)
                                                                           at com.jaychang.srv.behavior.SwipeToDismissItemCallback.getMovementFlags(SwipeToDismissItemCallback.java:37)
                                                                           at android.support.v7.widget.helper.ItemTouchHelper$Callback.getAbsoluteMovementFlags(ItemTouchHelper.java:1568)
                                                                           at android.support.v7.widget.helper.ItemTouchHelper.checkSelectForSwipe(ItemTouchHelper.java:960)
                                                                           at android.support.v7.widget.helper.ItemTouchHelper$2.onInterceptTouchEvent(ItemTouchHelper.java:340)
                                                                           at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2602)
                                                                           at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2730)
                                                                           at android.view.View.dispatchTouchEvent(View.java:10023)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                           at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:3070)
                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                           at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
                                                                           at android.view.View.dispatchPointerEvent(View.java:10243)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                           at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
02-05 22:28:13.372 19941-19941/com.jaychang.demo.srv E/AndroidRuntime:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                           at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6320)
                                                                           at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6372)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:615)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6169)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
02-05 22:28:13.729 904-15827/system_process E/ActivityManager: Found activity ActivityRecord{36079ba u0 com.jaychang.demo.srv/.MainActivity t2877 f} in proc activity list using null instead of expected ProcessRecord{64b8120 19941:com.jaychang.demo.srv/u0a307}
02-05 22:28:13.916 3326-3326/com.touchtype.swiftkey.beta E/FullInputEventModel: onStartInput event aborted: com.touchtype.keyboard.d.am: could not obtain extracted text (class com.touchtype.keyboard.d.am)

**Comment by jaychang0917** [comment]
Should be fixed in version `1.0.1`.
